// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package openapi

// User defines model for User.
type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
